//
//  MCSConsts.h
//  SJMediaCacheServer
//
//  Created by BlueDancer on 2020/11/25.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXPORT NSNotificationName const MCSFileWriteOutOfSpaceErrorNotification;

FOUNDATION_EXPORT NSString *const HLS_EXTENSION_PLAYLIST;
FOUNDATION_EXPORT NSString *const HLS_EXTENSION_SEGMENT;
FOUNDATION_EXPORT NSString *const HLS_EXTENSION_KEY;
FOUNDATION_EXPORT NSString *const HLS_EXTENSION_SUBTITLES;

FOUNDATION_EXPORT NSInteger const MCS_RESPONSE_CODE_OK;
FOUNDATION_EXPORT NSInteger const MCS_RESPONSE_CODE_PARTIAL_CONTENT;
FOUNDATION_EXPORT NSInteger const MCS_RESPONSE_CODE_BAD;

FOUNDATION_EXPORT NSString *const kLength;
NS_ASSUME_NONNULL_END
