#use_frameworks!

platform :ios, '8.0'

target 'SJMediaCacheServer_Example' do
  pod 'SJMediaCacheServer', :path => '../'

  pod 'SJVideoPlayer'
   
  pod 'SJUIKit/SQLite3', :podspec => 'https://gitee.com/changsanjiang/SJUIKit/raw/master/SJUIKit-YYModel.podspec'
  
  pod 'SJDownloadDataTask'
end
