#use_frameworks!

platform :ios, '12.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 12.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
      
      if config.name != 'Release'
        if target.name == 'SJBaseVideoPlayer'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) SJDEBUG'
        end
      end
      
    end
  end
  
#  installer.pod_target_subprojects.each do |project|
#    project.targets.each do |target|
#      target.build_configurations.each do |config|
#        if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
#          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
#        end
#      end
#    end
#  end
end

target 'SJMediaCacheServer_Example' do
  pod 'SJMediaCacheServer', :path => '../'

  pod 'SJVideoPlayer'
   
#  pod 'SJBaseVideoPlayer/AliPlayer'
  pod 'SJUIKit/SQLite3'#, :path => '/Users/bluedancer/Documents/GitHub/SJUIKit/SJUIKit.podspec'
  
#  pod 'KTVHTTPCache'
end
